'use client'
import {useEffect,useMemo,useState} from 'react'

const DAYS=['Push','Pull','Legs','Arms + Core','Full Body']
const PROGRAM={
 Push:[['Barbell Bench Press',3,6,8],['Incline Dumbbell Press',3,8,10],['Seated Dumbbell Shoulder Press',3,8,10],['Cable Lateral Raise',3,12,15],['Rope Triceps Pushdown',3,10,15],['Overhead Cable Triceps Extension',2,12,15]],
 Pull:[['Lat Pulldown',3,8,12],['Chest-Supported Row',3,8,12],['Single-Arm Cable Row',2,10,12],['Face Pull',3,12,15],['Incline Dumbbell Curl',3,8,12],['Hammer Curl',2,10,15]],
 Legs:[['Back Squat',3,6,8],['Romanian Deadlift',3,8,10],['Leg Press',3,10,12],['Seated Leg Curl',3,10,15],['Leg Extension',2,12,15],['Standing Calf Raise',3,10,15]],
 'Arms + Core':[['EZ-Bar Curl',3,8,12],['Cable Triceps Pushdown',3,8,12],['Incline Dumbbell Curl',3,10,12],['Overhead Cable Extension',3,10,12],['Cable Crunch',3,10,15],['Hanging Knee Raise',3,10,15],['Plank',2,30,60]],
 'Full Body':[['Trap Bar Deadlift',3,5,8],['Dumbbell Bench Press',3,8,10],['Bulgarian Split Squat',2,8,12],['Pull-Up / Assisted Pull-Up',3,6,10],['Cable Lateral Raise',2,12,15],['Farmer Carry',3,30,45]]
}
const LOADS={'Barbell Bench Press':40,'Incline Dumbbell Press':16,'Seated Dumbbell Shoulder Press':14,'Cable Lateral Raise':7.5,'Rope Triceps Pushdown':20,'Overhead Cable Triceps Extension':15,'Lat Pulldown':40,'Chest-Supported Row':35,'Single-Arm Cable Row':15,'Face Pull':15,'Incline Dumbbell Curl':10,'Hammer Curl':10,'Back Squat':50,'Romanian Deadlift':50,'Leg Press':100,'Seated Leg Curl':30,'Leg Extension':30,'Standing Calf Raise':40,'EZ-Bar Curl':20,'Cable Triceps Pushdown':20,'Overhead Cable Extension':15,'Cable Crunch':25,'Hanging Knee Raise':0,'Plank':0,'Trap Bar Deadlift':60,'Dumbbell Bench Press':18,'Bulgarian Split Squat':12,'Pull-Up / Assisted Pull-Up':0,'Farmer Carry':20}
const BB={
 'Shooting + Scoring':{focus:'Game-rep shooting, footwork and finishing',factor:.8,jumps:0,minutes:50},
 'Ball Handling + Creation':{focus:'Handle tightness, change of pace and separation',factor:.7,jumps:0,minutes:45},
 'Athleticism + Dunk':{focus:'Jump mechanics, unilateral power and landing control',factor:1.4,jumps:25,minutes:45},
 'Conditioning + Defense':{focus:'Repeat sprint ability, defensive movement and game conditioning',factor:1.3,jumps:10,minutes:45},
 'Recovery + Mobility':{focus:'Ankles, hips, T-spine and low-intensity movement',factor:.3,jumps:0,minutes:30}
}
const KEY='gym-training-os-v5'
const today=()=>new Date().toISOString().slice(0,10)
const daysSince=d=>(Date.now()-new Date(d))/86400000
const bbLoad=x=>Math.min(100,Math.max(0,Math.round(Number(x.duration)*Number(x.factor||1)+(Number(x.jumps)||0)*.7+(Number(x.intensity||3)-3)*7)))
const runLoad=x=>Math.min(100,Math.max(0,Math.round(Number(x.distance||0)*8+Number(x.duration||0)*.25+(Number(x.intensity||3)-3)*8)))
const base=()=>({history:[],sessions:[],bbLogs:[],runLogs:[],water:{},waterGoal:3000,loads:{},returnMode:true,phaseWeek:1})

export default function App(){
 const [tab,setTab]=useState('Today'),[day,setDay]=useState('Push'),[bb,setBb]=useState('Shooting + Scoring'),[state,setState]=useState(base),[logs,setLogs]=useState({}),[active,setActive]=useState(null),[now,setNow]=useState(Date.now())
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved)setState({...base(),...saved})}catch{}},[])
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}},[state])
 useEffect(()=>{if(!active?.running)return;const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[active])
 const elapsed=active?active.accumulated+(active.running?now-active.startedAt:0):0
 const recovery=useMemo(()=>{const bb7=state.bbLogs.filter(x=>daysSince(x.date)<7),run7=state.runLogs.filter(x=>daysSince(x.date)<7),load=bb7.reduce((a,x)=>a+x.load,0)+run7.reduce((a,x)=>a+x.load*.65,0),jumps=bb7.reduce((a,x)=>a+Number(x.jumps||0),0),leg=state.history.filter(x=>(x.day==='Legs'||x.day==='Full Body')&&daysSince(x.date)<4).length;const score=Math.max(0,Math.min(100,Math.round(100-Math.min(55,load*.7)-Math.min(20,jumps*.35)-Math.min(12,leg*4))));return{score,status:score>=70?'READY':score>=45?'MODERATE':'PROTECT',scale:score>=70?1:score>=45?.9:.8,load,jumps}},[state])
 const start=(type,name,meta={})=>setActive({type,name,meta,startedAt:Date.now(),accumulated:0,running:true})
 const pause=()=>setActive(a=>({...a,accumulated:a.accumulated+(Date.now()-a.startedAt),running:false}))
 const resume=()=>setActive(a=>({...a,startedAt:Date.now(),running:true}))
 const finish=()=>{if(!active)return;const duration=Math.max(1,Math.round(elapsed/60000));const session={date:today(),type:active.type,name:active.name,duration,...active.meta};setState(s=>({...s,sessions:[...s.sessions,session],bbLogs:active.type==='basketball'?[...s.bbLogs,{date:today(),type:active.name,duration:active.meta.duration,intensity:active.meta.intensity,jumps:active.meta.jumps,factor:active.meta.factor||1,load:active.meta.load}]:s.bbLogs,runLogs:active.type==='cardio'?[...s.runLogs,{date:today(),...active.meta}]:s.runLogs}));setActive(null);if(active.type==='gym')setTab('Progress')}
 const gymScale=(day==='Legs'||day==='Full Body')?recovery.scale:1
 const gymEntries=PROGRAM[day].map(e=>({...e,load:Math.round((state.loads[e[0]]??LOADS[e[0]]??0)*gymScale*2)/2}))
 const saveGym=()=>{const entries=PROGRAM[day].flatMap((e,i)=>logs[i]?.done?[{date:today(),day,exercise:e[0],weight:Number(logs[i].weight??LOADS[e[0]]),reps:Array.from({length:e[1]},(_,s)=>Number(logs[i]['r'+s]??e[3])),rir:Number(logs[i].rir??2)}]:[]).map(x=>({...x,volume:x.weight*x.reps.reduce((a,b)=>a+b,0),pr:false}));if(!entries.length)return;setState(s=>({...s,history:[...s.history.filter(x=>!(x.date===today()&&x.day===day)),...entries],sessions:[...s.sessions,{date:today(),type:'gym',name:day,duration:Math.max(1,Math.round(elapsed/60000)),sets:entries.length}]}));setLogs({})}
 return <main><Header state={state} setState={setState}/><div className="shell"><nav>{['Today','Basketball','Cardio','Programme','Progress','Settings'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav>
 {tab==='Today'&&<Today day={day} setDay={d=>{setDay(d);setLogs({})}} state={state} setState={setState} recovery={recovery} gymEntries={gymEntries} logs={logs} setLogs={setLogs} start={start} saveGym={saveGym} gymScale={gymScale}/>} 
 {tab==='Basketball'&&<Basketball bb={bb} setBb={setBb} state={state} start={start}/>} {tab==='Cardio'&&<Cardio start={start} state={state}/>} {tab==='Programme'&&<Programme state={state}/>} {tab==='Progress'&&<Progress state={state} recovery={recovery}/>} {tab==='Settings'&&<Settings state={state} setState={setState}/>}</div><Footer tab={tab} setTab={setTab}/>{active&&<Workout active={active} elapsed={elapsed} pause={pause} resume={resume} finish={finish} cancel={()=>setActive(null)}/>}</main>
}
function Header({state,setState}){return <header><div className="brand"><div className="logo">G</div><div><b>GYM</b><span>TRAINING OS · V5</span></div></div><button className="mode" onClick={()=>setState(x=>({...x,returnMode:!x.returnMode}))}>{state.returnMode?'RETURN PHASE':'TRAINING DAY'}</button></header>}
function Today({day,setDay,state,setState,recovery,gymEntries,logs,setLogs,start,saveGym,gymScale}){return <><section className="hero"><div><label>{state.returnMode?`RETURN PHASE · WEEK ${state.phaseWeek}`:'TRAINING DAY'}</label><h1>{day}</h1><p>{state.returnMode?'Rebuild capacity, keep 2–3 RIR and let recovery shape volume.':'Normal progressive training day with recovery-aware lower-body adjustments.'}</p></div><div className="readiness"><strong>{recovery.score}</strong><span>READINESS</span></div></section><section className="phase"><div><b>Return Phase vs Training Day</b><p><strong>Return Phase</strong> is the multi-week block. <strong>Training Day</strong> is the workout inside it. Phase → Week → Day → Exercises.</p></div></section><section className="grid2"><Readiness recovery={recovery}/><Water state={state} setState={setState}/></section><div className="dayRow">{DAYS.map(d=><button className={day===d?'sel':''} onClick={()=>setDay(d)} key={d}>{d}</button>)}</div>{gymScale<1&&<div className="notice">Lower-body volume is currently {Math.round(gymScale*100)}% because recent court/run load is elevated.</div>}<div className="sectionTitle"><div><label>TODAY'S WORK</label><h2>{gymEntries.length} exercises</h2></div><button className="primary" onClick={()=>start('gym',day,{sets:gymEntries.length})}>▶ Start Workout</button></div><div className="exercises">{gymEntries.map((e,i)=><Exercise key={e[0]} e={e} log={logs[i]||{}} setLog={x=>setLogs(m=>({...m,[i]:{...m[i],...x}}))}/>)}</div><button className="finish" onClick={saveGym}>✓ Save Completed Workout</button></>}
function Exercise({e,log,setLog}){return <article className={log.done?'exercise done':'exercise'}><div className="exerciseHead"><span>EX</span><div><b>{e[0]}</b><small>{e[1]} sets · {e[2]}–{e[3]} reps</small></div><strong>{e.load||'BW'}<em>kg</em></strong></div><div className="sets">{Array.from({length:e[1]},(_,s)=><div className="set" key={s}><span>{s+1}</span><input value={log.weight??e.load} onChange={x=>setLog({weight:x.target.value})}/><input value={log['r'+s]??e[3]} onChange={x=>setLog({['r'+s]:x.target.value})}/><button className={log['s'+s]?'checked':''} onClick={()=>setLog({['s'+s]:!log['s'+s]})}>✓</button></div>)}</div><div className="exerciseFoot"><label>RIR <select value={log.rir??2} onChange={x=>setLog({rir:x.target.value})}><option>0</option><option>1</option><option>2</option><option>3</option></select></label><button onClick={()=>setLog({done:!log.done})}>{log.done?'✓ Logged':'Mark complete'}</button></div></article>}
function Readiness({recovery}){return <section className="card"><label>BASKETBALL + CARDIO LOAD</label><div className="loadLine"><div><b>{recovery.status}</b><span>{Math.round(recovery.load)} recent load · {recovery.jumps} jumps</span></div><strong>{recovery.score}/100</strong></div></section>}
function Water({state,setState}){const d=today(),intake=Number(state.water[d]||0),goal=Number(state.waterGoal||3000),pct=Math.min(100,Math.round(intake/goal*100));const add=n=>setState(x=>({...x,water:{...x.water,[d]:intake+n}}));return <section className="card"><div className="cardTitle"><label>HYDRATION</label><b>{(intake/1000).toFixed(2)} / {(goal/1000).toFixed(1)} L</b></div><div className="bar"><i style={{width:pct+'%'}}/></div><div className="actions"><button onClick={()=>add(250)}>+250 ml</button><button onClick={()=>add(500)}>+500 ml</button><button onClick={()=>add(750)}>+750 ml</button></div></section>}
function Basketball({bb,setBb,start}){const w=BB[bb],[duration,setDuration]=useState(w.minutes),[intensity,setIntensity]=useState(3),[jumps,setJumps]=useState(w.jumps),load=bbLoad({duration,intensity,jumps,factor:w.factor});return <section><section className="hero"><div><label>BASKETBALL OS</label><h1>{bb}</h1><p>{w.focus}</p></div><div className="readiness"><strong>{load}</strong><span>SESSION LOAD</span></div></section><div className="chips">{Object.keys(BB).map(x=><button className={bb===x?'active':''} onClick={()=>setBb(x)} key={x}>{x}</button>)}</div><section className="card form"><label>SESSION INPUTS</label><div className="formGrid"><Field label="Duration (min)" value={duration} set={setDuration}/><Field label="Intensity 1–5" value={intensity} set={setIntensity}/><Field label="Jumps" value={jumps} set={setJumps}/></div><button className="primary full" onClick={()=>start('basketball',bb,{duration:Number(duration),intensity:Number(intensity),jumps:Number(jumps),factor:w.factor,load})}>▶ Start Basketball Workout</button></section></section>}
function Cardio({start,state}){const [distance,setDistance]=useState(5),[duration,setDuration]=useState(30),[intensity,setIntensity]=useState(3),load=runLoad({distance,duration,intensity});return <section><section className="hero"><div><label>CARDIO OS</label><h1>Runs</h1><p>Log distance and duration. Run load feeds the same recovery model as basketball.</p></div><div className="readiness"><strong>{load}</strong><span>RUN LOAD</span></div></section><section className="card form"><label>RUN INPUTS</label><div className="formGrid"><Field label="Distance (km)" value={distance} set={setDistance}/><Field label="Duration (min)" value={duration} set={setDuration}/><Field label="Intensity 1–5" value={intensity} set={setIntensity}/></div><button className="primary full" onClick={()=>start('cardio','Run',{distance:Number(distance),duration:Number(duration),intensity:Number(intensity),load})}>▶ Start Cardio</button></section><div className="card"><label>RECENT RUNS</label>{state.runLogs.slice(-6).reverse().map((x,i)=><div className="row" key={i}><span>{x.date}</span><b>{x.distance} km · {x.duration} min</b><strong>{x.load}</strong></div>)}</div></section>}
function Field({label,value,set}){return <label>{label}<input type="number" value={value} onChange={e=>set(e.target.value)}/></label>}
function Programme({state}){return <section><section className="hero"><div><label>PROGRAMME OS</label><h1>Return Phase</h1><p>Week {state.phaseWeek}: rebuild consistency before chasing load.</p></div></section><div className="phaseSteps"><span>PHASE</span><b>→</b><span>WEEK</span><b>→</b><span>TRAINING DAY</span><b>→</b><span>EXERCISES</span></div><div className="dayGrid">{DAYS.map((d,i)=><div className="card" key={d}><label>DAY 0{i+1}</label><h2>{d}</h2><p>{PROGRAM[d].length} exercises · recovery-aware lower-body volume.</p></div>)}</div><section className="card rules"><h2>Training structure</h2><p><b>Return Phase:</b> multi-week context controlling training intensity and recovery.</p><p><b>Training Day:</b> the actual Push, Pull, Legs, Arms + Core or Full Body session.</p><p><b>Basketball protection:</b> court and run load can reduce lower-body volume.</p></section></section>}
function Progress({state,recovery}){const week=x=>daysSince(x.date)<7,gym=state.sessions.filter(x=>week(x)&&x.type==='gym'),bb=state.bbLogs.filter(week),runs=state.runLogs.filter(week),km=runs.reduce((a,x)=>a+Number(x.distance||0),0),load=bb.reduce((a,x)=>a+x.load,0)+runs.reduce((a,x)=>a+x.load,0);return <section><section className="hero"><div><label>TRAINING DATA</label><h1>Progress</h1><p>Your overall week across strength, basketball, cardio and hydration.</p></div></section><div className="stats"><div><b>{gym.length}</b><span>gym</span></div><div><b>{bb.length}</b><span>basketball</span></div><div><b>{km.toFixed(1)}</b><span>run km</span></div><div><b>{Math.round(load)}</b><span>court + run load</span></div></div><section className="card"><label>RECOVERY</label><div className="loadLine"><div><b>{recovery.status}</b><span>Recent basketball + cardio workload</span></div><strong>{recovery.score}/100</strong></div></section><section className="card"><label>WEEK LOG</label>{state.sessions.slice(-12).reverse().map((x,i)=><div className="row" key={i}><span>{x.date}</span><b>{x.type.toUpperCase()} · {x.name}</b><strong>{x.duration}m</strong></div>)}{!state.sessions.length&&<p className="muted">Complete a session to build your weekly record.</p>}</section></section>}
function Settings({state,setState}){return <section><section className="hero"><div><label>SETTINGS</label><h1>Training OS</h1><p>Set your return-phase week and starting loads.</p></div></section><section className="card"><label>RETURN PHASE WEEK</label><div className="formGrid one"><Field label="Week" value={state.phaseWeek} set={v=>setState(x=>({...x,phaseWeek:Number(v)}))}/></div></section><section className="card"><label>STARTING LOADS</label>{Object.entries(LOADS).map(([x,v])=><div className="loadRow" key={x}><span>{x}</span><input type="number" step="0.5" value={state.loads[x]??v} onChange={e=>setState(s=>({...s,loads:{...s.loads,[x]:Number(e.target.value)}}))}/><small>kg</small></div>)}</section></section>}
function Workout({active,elapsed,pause,resume,finish,cancel}){const mins=Math.floor(elapsed/60000),secs=Math.floor(elapsed/1000)%60;return <div className="overlay"><div className="workout"><label>ACTIVE WORKOUT</label><h1>{active.name}</h1><div className="clock">{String(mins).padStart(2,'0')}:{String(secs).padStart(2,'0')}</div><p>{active.running?'Session running':'Session paused'} · {active.type.toUpperCase()}</p><div className="workBtns">{active.running?<button onClick={pause}>Ⅱ Pause</button>:<button onClick={resume}>▶ Resume</button>}<button className="primary" onClick={finish}>✓ Finish & Save</button></div><button className="cancel" onClick={cancel}>Exit without saving</button></div></div>}
function Footer({tab,setTab}){return <footer>{['Today','Basketball','Cardio','Progress'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x==='Today'?'GYM':x==='Basketball'?'COURT':x.toUpperCase()}</button>)}</footer>}
